language: python
python:
  - "3.6"
env:
  - CODECOV_TOKEN="c95d89c0-2958-4ba2-a19f-7fe7a4e76c9a"
before_install:
  - wget https://github.com/copasi/COPASI/releases/download/Build-207/COPASI-4.25.207-Linux-64bit.tar.gz -O /tmp/copasi.tar.gz
  - tar -xzvf /tmp/copasi.tar.gz
  - export PATH=$PATH:$PWD/COPASI-4.25.207-Linux-64bit/bin/
install:
  - pip install -r requirements.txt
  - pip install .
script: 
  - nosetests --with-coverage
branches:
  only:
    - develop
    - master
after_success:
  - codecov

