#!/bin/bash
cd $1
sed -i 's/ReportType/report_type/g' *.ipynb
sed -i 's/Metabolites/metabolites/g' *.ipynb
sed -i 's/GlobalQuantities/global_quantities/g' *.ipynb
sed -i 's/QuantityType/quantity_type/g' *.ipynb
sed -i 's/ReportName/report_name/g' *.ipynb
sed -i 's/Append/append/g' *.ipynb
sed -i 's/ConfirmOverwrite/confirm_overwrite/g' *.ipynb
sed -i 's/Save/save/g' *.ipynb
sed -i 's/Variable/variable/g' *.ipynb
sed -i 's/ConfigFilename/config_filename/g' *.ipynb
sed -i 's/OverwriteConfigFile/overwrite_config_file/g' *.ipynb
sed -i 's/UpdateModel/update_model/g' *.ipynb
sed -i 's/RandomizeStartValues/randomize_start_values/g' *.ipynb
sed -i 's/CreateParameterSets/create_parameter_sets/g' *.ipynb
sed -i 's/CalculateStatistics/calculate_statistics/g' *.ipynb
sed -i 's/Method/method/g' *.ipynb
sed -i 's/PopulationSize/population_size/g' *.ipynb
sed -i 's/RandomNumberGenerator/random_number_generator/g' *.ipynb
sed -i 's/Seed/seed/g' *.ipynb
sed -i 's/Pf/pf/g' *.ipynb
sed -i 's/IterationLimit/iteration_limit/g' *.ipynb
sed -i 's/Tolerance/tolerance/g' *.ipynb
sed -i 's/Rho/rho/g' *.ipynb
sed -i 's/Scale/scale/g' *.ipynb
sed -i 's/SwarmSize/swarm_size/g' *.ipynb
sed -i 's/StdDeviation/std_deviation/g' *.ipynb
sed -i 's/NumberOfIterations/number_of_iterations/g' *.ipynb
sed -i 's/StartTemperature/start_temperature/g' *.ipynb
sed -i 's/CoolingFactor/cooling_factor/g' *.ipynb
sed -i 's/RowOrientation/row_orientation/g' *.ipynb
sed -i 's/ExperimentType/experiment_type/g' *.ipynb
sed -i 's/FirstRow/first_row/g' *.ipynb
sed -i 's/NormalizeWeightsPerExperiment/normalize_weights_per_experiment/g' *.ipynb
sed -i 's/RowContainingNames/row_containing_names/g' *.ipynb
sed -i 's/Separator/separator/g' *.ipynb
sed -i 's/WeightMethod/weight_method/g' *.ipynb
sed -i 's/PruneHeaders/prune_headers/g' *.ipynb
sed -i 's/Scheduled/scheduled/g' *.ipynb
sed -i 's/UseTemplateStartValues/use_config_start_values/g' *.ipynb
sed -i 's/LowerBound/lower_bound/g' *.ipynb
sed -i 's/UpperBound/upper_bound/g' *.ipynb
sed -i 's/Run/run/g' *.ipynb
sed -i 's/Plot/plot/g' *.ipynb
sed -i 's/FontSize/font_size/g' *.ipynb
sed -i 's/AxisSize/axis_size/g' *.ipynb
sed -i 's/ExtraTitle/extra_title/g' *.ipynb
sed -i 's/LineWidth/line_width/g' *.ipynb
sed -i 's/DotSize/marker_size/g' *.ipynb
sed -i 's/SaveFig/savefig/g' *.ipynb
sed -i 's/TitleWrapSize/title_wrap_size/g' *.ipynb
sed -i 's/Show/show/g' *.ipynb
sed -i 's/Ylimit/ylimit/g' *.ipynb
sed -i 's/Xlimit/xlimit/g' *.ipynb
sed -i 's/DPI/dpi/g' *.ipynb
sed -i 's/XTickRotation/xtick_rotation/g' *.ipynb
sed -i 's/LegendLoc/legend_loc/g' *.ipynb
sed -i 's/ScanType/scan_type/g' *.ipynb
sed -i 's/SubTask/subtask/g' *.ipynb
sed -i 's/OutputInSubtask/output_in_subtask/g' *.ipynb
sed -i 's/AdjustInitialConditions/adjust_initial_conditions/g' *.ipynb
sed -i 's/NumberOfSteps/number_of_steps/g' *.ipynb
sed -i 's/Maximum/maximum/g' *.ipynb
sed -i 's/Minimum/minimum/g' *.ipynb
sed -i 's/Log/log10/g' *.ipynb
sed -i 's/DistributionType/distribution_type/g' *.ipynb
sed -i 's/ClearScans/clear_scans/g' *.ipynb
sed -i 's/Mode/mode/g' *.ipynb
sed -i 's/MaxTime/max_time/g' *.ipynb
sed -i 's/Index/index/g' *.ipynb
sed -i 's/ParameterDict/parameter_dict/g' *.ipynb
sed -i 's/DF/df/g' *.ipynb
sed -i 's/ParameterPath/parameter_path/g' *.ipynb
sed -i 's/OutputDir/output_dir/g' *.ipynb
sed -i 's/CopyNumber/copy_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb

sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb

sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb
sed -i 's/NumberOfPEs/pe_number/g' *.ipynb

